#spring boot 2.0之前的配置方式
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
spring:
  #spring boot 2.0之后的配置方式
  #配置 eureka 登录密码，输入地址 http://localhost:8761 时候就需要输入这个用户名密码登录进去
#  security:
#    user:
#      name: admin
#      password: admin
  application:
    name: 003-discovery-eureka
#日志
logging:
  level:
    org:
      springframework:
        security: DEBUG
#web服务端口
server:
  port: 8761
#eureka配置
eureka:
  instance:
    # ${HOSTNAME} 是系统变量，也可以直接使用localhost指定
    hostname: ${java.rmi.server.hostname}
    # 服务向eureka注册时使用IP 而不是 hostname
    prefer-ip-address: true
  client:
    #只作为eureka Server,不用注册到eureka服务中心（standalone模式使用）
    register-with-eureka: false #是否将自己注册到Eureka Server，默认为true
    fetch-registry: false #是否从Eureka Server获取注册信息，默认为true。
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    #Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒
    wait-time-in-ms-when-sync-empty: 0