spring:
  application:
    name: 011-discovery-eureka-ha
---
server:
  port: 8761
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
server:
  port: 8762
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/

---
server:
  port: 8763
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
