spring:
  application:
    name: _005_consumer_movie_eureka
server:
  port: 8081
  servlet:
    path: /
user:
  #注意这里的路径为eureka中查询到的服务提供路径
  userServicePath: http://localhost:8080/user/
eureka:
  client:
    # EurekaClientAutoConfiguration
    prefer-ip-address: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka
    #EurekaDiscoveryClientConfiguration类中定义
    healthcheck:
      enabled: true
  instance:
    hostname: ${java.rmi.server.hostname}
    # 默认为 ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: ${server.servlet.path}/info
    healthCheckUrlPath: ${server.servlet.path}/health
    homePageUrl: ${eureka.hostname}/