spring:
  application:
    name: 006-consumer-movie-eureka-ribbon
server:
  port: 8081
  servlet:
    path: /
#user:
#  #做负载均衡的时候，不需要这个动态配置的地址
#  userServicePath: http://localhost:8080/user/
eureka:
  client:
    # EurekaClientAutoConfiguration
    prefer-ip-address: true
    #spring boot 2.0之后的属性名
#    service-url:
    #spring boot 2.0之前的属性名
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka
    #EurekaDiscoveryClientConfiguration类中定义
    healthcheck:
      enabled: true
  instance:
    hostname: ${java.rmi.server.hostname}
    # 默认为 ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: ${server.servlet.path}/info
    healthCheckUrlPath: ${server.servlet.path}/health
    homePageUrl: ${eureka.instance.hostname}/