spring:
  application:
    name: 014-consumer-movie-hystrix-particle
server:
  port: 8081
  servlet:
      path: /
eureka:
  client:
      # EurekaClientAutoConfiguration spring boot 2.0之后的属性名
    prefer-ip-address: true
    #spring boot 2.0之后的属性名
#    service-url:
    #spring boot 2.0之前的属性名
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka
    #EurekaDiscoveryClientConfiguration 类中定义
    healthcheck:
      enabled: true
  instance:
    hostname: ${java.rmi.server.hostname}
    # 默认为 ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: ${server.servlet.path}/info
    healthCheckUrlPath: ${server.servlet.path}/health
    homePageUrl: ${eureka.instance.hostname}/
    prefer-ip-address: true
logging:
  level:
    root: info
    org.springframework: debug
    cn.mylava: debug
    #这个日志级别设置没有用，需要单独在FeignConfiguration中设置日志级别
#    cn.mylava.facade: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #设置hystrix超时时间5秒,默认时间为1秒
            timeoutInMilliseconds: 5000
#全局禁用hystrix,这里演示局部，所以注释掉
#feign:
#  hystrix:
#    enabled: false
